# Generated by Django 2.0.2 on 2018-07-22 19:53

import delivery.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecurityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn_number', localflavor.us.models.USSocialSecurityNumberField(max_length=11)),
                ('ssn_img', models.ImageField(default='ssn.jpg', upload_to=delivery.models.user_directory_path)),
                ('dl_state', localflavor.us.models.USStateField(max_length=2)),
                ('dl_number', models.CharField(max_length=11)),
                ('dlside1_img', models.ImageField(default='dlside1.jpg', upload_to=delivery.models.user_directory_path)),
                ('dlside2_img', models.ImageField(default='dlside2.jpg', upload_to=delivery.models.user_directory_path)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usersecurity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
