# Generated by Django 2.0.2 on 2018-07-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20180722_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersecurityinfo',
            name='dl_number',
            field=models.CharField(max_length=13),
        ),
    ]
