# Generated by Django 2.0.2 on 2018-08-08 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_description', models.CharField(max_length=255)),
                ('package_descriptionhid', models.CharField(max_length=255)),
                ('package_descriptionplus', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='testpackage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
