# Generated by Django 2.0.2 on 2018-08-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtest', '0002_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='driving_duration',
            field=models.CharField(default='0.0', max_length=50),
        ),
    ]
