# Generated by Django 2.0.2 on 2018-08-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtest', '0003_auto_20180810_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='driving_duration',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
