# Generated by Django 2.0.2 on 2018-07-26 10:27

import delivery.models
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(help_text='To generate the map for your location', srid=4326)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='useraddress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pic', models.FileField(default='image.jpg', upload_to=delivery.models.user_directory_path)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Please make sure phone number format: '+199999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Trans', 'Transgender')], max_length=11)),
                ('date_of_birth', models.DateField(max_length=8)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSecurityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn_number', localflavor.us.models.USSocialSecurityNumberField(max_length=11)),
                ('ssn_img', models.ImageField(default='ssn.jpg', upload_to=delivery.models.user_directory_path)),
                ('dl_state', localflavor.us.models.USStateField(max_length=2)),
                ('dl_number', models.CharField(max_length=13)),
                ('dlside1_img', models.ImageField(default='dlside1.jpg', upload_to=delivery.models.user_directory_path)),
                ('dlside2_img', models.ImageField(default='dlside2.jpg', upload_to=delivery.models.user_directory_path)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usersecurity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
