# Generated by Django 2.0.2 on 2018-07-26 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='contact_phone',
            field=models.CharField(default='', max_length=17, validators=[django.core.validators.RegexValidator(message="Please make sure phone number format: '+199999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='point_of_contact',
            field=models.CharField(default='', max_length=255),
        ),
    ]
