# Generated by Django 2.0.2 on 2018-08-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20180727_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='lang',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
    ]
