# Generated by Django 2.0.2 on 2018-08-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20180813_0500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='lang',
            new_name='lng',
        ),
    ]
