# Generated by Django 2.0.2 on 2018-07-06 11:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Please make sure phone number format: '+199999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Trans', 'Transgender')], max_length=5)),
                ('date_of_birth', models.DateField(max_length=8)),
                ('ssn_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Please enter vallid Social Security Number', regex='^(?!000|666)[0-8][0-9]{2}-(?!00)[0-9]{2}-(?!0000)[0-9]{4}$')])),
                ('num_delivery_created', models.IntegerField(default=0)),
                ('num_delivery_made', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('dl_state', models.CharField(max_length=2)),
                ('dl_number', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
