# Generated by Django 2.0.2 on 2018-07-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='dl_number',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='dl_state',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='num_delivery_created',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='num_delivery_made',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='ssn_number',
        ),
    ]
