# Generated by Django 2.0.2 on 2018-08-25 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_searched', models.DateTimeField(auto_now_add=True)),
                ('search_adrs', models.CharField(max_length=255)),
                ('search_adrs_lat', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('search_adrs_lng', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usersearch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
