# Generated by Django 2.0.2 on 2018-07-07 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('pickup_adrs', models.CharField(max_length=100)),
                ('delivery_adrs', models.CharField(max_length=100)),
                ('delivery_distance', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('expected_deliveryby', models.DateTimeField()),
                ('package_label', models.CharField(max_length=100)),
                ('package_type', models.CharField(max_length=100)),
                ('package_desc', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MakeDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickuprequested_at', models.DateTimeField(auto_now_add=True)),
                ('pickupaccespted_at', models.DateTimeField(auto_now_add=True)),
                ('picked_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_deliverytime', models.DateTimeField()),
                ('current_status', models.CharField(max_length=100)),
                ('delivery_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.CreateDelivery')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Trans', 'Transgender')], max_length=5)),
                ('date_of_birth', models.DateField(max_length=8)),
                ('all_given', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
