# Generated by Django 2.0.2 on 2018-07-12 00:29

import delivery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20180709_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='user_pic',
            field=models.FileField(default='image.jpg', upload_to=delivery.models.user_directory_path),
        ),
    ]
