# Generated by Django 2.0.2 on 2018-07-29 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0004_auto_20180727_0450'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('package_type', models.CharField(choices=[('Food', 'Food'), ('Grocery', 'Grocery'), ('Documents', 'Documents'), ('Humanwear', 'Humanwear'), ('Homewear', 'Homewear'), ('Health', 'Health'), ('Medicine', 'Medicine'), ('Electronics', 'Electronics')], max_length=50)),
                ('package_description', models.CharField(max_length=255)),
                ('package_weight', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('package_dimensions', models.CharField(max_length=255)),
                ('package_value', models.CharField(max_length=255)),
                ('delivery_timeline', models.CharField(choices=[('Within 2 Hours', 'Within 2 Hours'), ('Within 4 Hours', 'Within 4 Hours'), ('Same day Delivery(24x1)', 'Same day Delivery(24x1)'), ('Two day Delivery(24x2)', 'Two day Delivery(24x2)'), ('Within a Week(24x7)', 'Within a Week(24x7)'), ('Within Two Weeks', 'Within Two Weeks'), ('Within a Month', 'Within a Month'), ('Within Three Months', 'Within Three Months'), ('Within Six Months', 'Within Six Months')], max_length=50)),
                ('shipping_distance', models.IntegerField(max_length=255)),
                ('shipping_charge', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('payment_status', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userpackage', to=settings.AUTH_USER_MODEL)),
                ('delivery_adrs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='delivery.UserAddress')),
                ('pickup_adrs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='delivery.UserAddress')),
            ],
        ),
    ]
