# Generated by Django 2.0.2 on 2018-07-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackage',
            name='shipping_distance',
            field=models.IntegerField(),
        ),
    ]
