# Generated by Django 2.0.2 on 2018-07-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmanage', '0002_auto_20180728_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackage',
            name='delivery_timeline',
            field=models.CharField(choices=[('Within 2 Hours', 'Within 2 Hours'), ('Within 4 Hours', 'Within 4 Hours'), ('Same day Delivery(24x1)', 'Same day Delivery(24x1)'), ('Three day Delivery(24x3)', 'Three day Delivery(24x3)'), ('Within a Week(24x7)', 'Within a Week(24x7)'), ('Within Two Weeks', 'Within Two Weeks'), ('Within a Month', 'Within a Month'), ('Within Three Months', 'Within Three Months'), ('Within Six Months', 'Within Six Months')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userpackage',
            name='package_dimensions',
            field=models.CharField(choices=[('Small (Under 15 x 12 x 1)', 'Small (Under 15 x 12 x 1)'), ('Medium (Under 15 x 12 x 6)', 'Medium (Under 15 x 12 x 6)'), ('Large (Under 24 x 12 x 6)', 'Large (Under 24 x 12 x 6)')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userpackage',
            name='package_weight',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userpackage',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userpackage',
            name='shipping_distance',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
