# Generated by Django 2.0.2 on 2018-08-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmanage', '0003_auto_20180729_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpackage',
            name='shipping_distance',
        ),
        migrations.AddField(
            model_name='userpackage',
            name='bicycling_distance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userpackage',
            name='bicycling_duration',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userpackage',
            name='driving_distance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userpackage',
            name='driving_duration',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userpackage',
            name='transit_distance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userpackage',
            name='transit_duration',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userpackage',
            name='shipping_charge',
            field=models.CharField(default='5', max_length=255),
        ),
    ]
