# Generated by Django 2.0.2 on 2018-08-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmanage', '0004_auto_20180801_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackage',
            name='package_value',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
