# Generated by Django 2.0.2 on 2018-08-15 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmanage', '0005_auto_20180810_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackage',
            name='delivery_adrs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deliverya', to='delivery.UserAddress'),
        ),
        migrations.AlterField(
            model_name='userpackage',
            name='pickup_adrs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickupa', to='delivery.UserAddress'),
        ),
    ]
