# Generated by Django 2.0.2 on 2018-08-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmanage', '0006_auto_20180815_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpackage',
            name='pickup_adrs_lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
    ]
