# Generated by Django 2.0.2 on 2018-08-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmanage', '0007_userpackage_pickup_adrs_lat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpackage',
            name='pickup_adrs_val',
            field=models.IntegerField(default=0),
        ),
    ]
