# Generated by Django 2.0.2 on 2018-08-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmanage', '0008_userpackage_pickup_adrs_val'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpackage',
            name='pickup_adrs_val',
        ),
        migrations.AddField(
            model_name='userpackage',
            name='pickup_adrs_lng',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
    ]
